### ISSUE TITLE
setMovie is not a Function

### ISSUE THREAD

**Issue by MitchelAlvarez** [midudev/aprendiendo-react#96]
Muy buenas noches, llevo ya un buen rato tratando de entender porque me sale este error.
Contexto, después de ver el video de la API de movies trato de hacerlo yo solo, ahorita solo quise ver si entendía bien el fetch o no, pero no entiendo porque me sale este error, yo se que estoy lejos de terminar, pero espero puedan ayudarme.
![image](https://github.com/midudev/aprendiendo-react/assets/99301935/956f1cf7-6d4a-4ea8-8979-0e6acb4d040b)

**Comment by RoAriel** [comment]
Hola Mitchel, no quiero equivocarme pero al usar el useState tenes que usarlo de la siguiente manera
const [movies, setMovies] = userState([])

Saludos.

**Comment by MitchelAlvarez** [comment]
@RoAriel estoy que me muero de la pena, ayer en verdad me tarde mas de 3 o 4 horas moviéndole, investigando fetch, async, promise y nunca nunca vi que puse {} en vez de []
Miiiiiiiil gracias
